name: twf_pos
description: "A new Flutter project."
publish_to: 'none'

version: 1.7.2+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  app_settings: ^5.1.1
  badges: ^3.1.2
  barcode_scan2: ^4.5.1
  cached_network_image: ^3.4.1
  change_app_package_name: ^1.4.0
  connectivity_plus: ^6.1.1
  cron: ^0.6.1
  cupertino_icons: ^1.0.8
  flutter_date_pickers: ^0.4.3
  flutter_datetime_picker_plus: ^2.2.0
  dio: ^5.7.0
  htmltopdfwidgets: ^1.0.5
  flutter_kurdish_localization: ^1.1.0
  fluttertoast: ^8.2.10
  geolocator: ^13.0.2
  get_ip_address: ^0.0.7
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  printing: ^5.13.4
  provider: ^6.1.2
  qr: ^3.0.2
  sqflite: ^2.4.1
  shared_preferences: ^2.3.4
  search_choices: ^2.3.1
  share_plus: ^10.1.3
  url_launcher: ^6.3.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/TWF.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - i18n/

# إزالة dependency_overrides لتجنب التعارض
# dependency_overrides:
#   intl: 0.20.2
